name: MSYS2 Windows Build

on:
  push:
    branches:
      - main

jobs:
  build_and_artifact:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: git mingw-w64-ucrt-x86_64-gcc make

      - name: Build ldecod
        run: |
          cd ldecod
          make

      - name: Prepare artifact
        run: |
          # You can still rename it if you like
          mv bin/ldecod.exe ldecod-main-latest.exe

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ldecod-latest-build # Name of the artifact bundle
          path: ldecod-main-latest.exe # Path to the file to upload